/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TagsImport } from './routes/tags'
import { Route as IndexImport } from './routes/index'
import { Route as ResultsItemcountIndexImport } from './routes/results/$itemcount/index'
import { Route as ResultsItemcountKeywordsIndexImport } from './routes/results/$itemcount/$keywords/index'

// Create/Update Routes

const TagsRoute = TagsImport.update({
  path: '/tags',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ResultsItemcountIndexRoute = ResultsItemcountIndexImport.update({
  path: '/results/$itemcount/',
  getParentRoute: () => rootRoute,
} as any)

const ResultsItemcountKeywordsIndexRoute =
  ResultsItemcountKeywordsIndexImport.update({
    path: '/results/$itemcount/$keywords/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsImport
      parentRoute: typeof rootRoute
    }
    '/results/$itemcount/': {
      id: '/results/$itemcount/'
      path: '/results/$itemcount'
      fullPath: '/results/$itemcount'
      preLoaderRoute: typeof ResultsItemcountIndexImport
      parentRoute: typeof rootRoute
    }
    '/results/$itemcount/$keywords/': {
      id: '/results/$itemcount/$keywords/'
      path: '/results/$itemcount/$keywords'
      fullPath: '/results/$itemcount/$keywords'
      preLoaderRoute: typeof ResultsItemcountKeywordsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  TagsRoute,
  ResultsItemcountIndexRoute,
  ResultsItemcountKeywordsIndexRoute,
})

/* prettier-ignore-end */
